services:
  sharp_system_db:
    image: postgres:16-alpine
    container_name: postgres-database
    restart: always
    environment:
      POSTGRES_USER: aeon-logics
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sharp_system
    ports:
      - "5432:5432"
    volumes:
      - sharp_system_db_data:/var/lib/postgresql/data

volumes:
  sharp_system_db_data:
